/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.04
    max_hamming: 0

    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: pnp

    tag:
      ids: [0, 1, 2]
      frames: [left_wrist_apriltag_00, left_wrist_apriltag_01, left_wrist_apriltag_02]
      sizes: [0.04, 0.04, 0.04]
